# Generated by Django 4.2.5 on 2024-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
