# Generated by Django 4.2.5 on 2024-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=40)),
                ('std_email', models.EmailField(max_length=254)),
                ('std_age', models.IntegerField(max_length=50)),
                ('std_passwrod', models.CharField(max_length=50)),
            ],
        ),
    ]
